# -*- coding: utf-8 -*-
"""Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BLBg_DPacGQmzkMOwfvA57zNSCPg5a8
"""

from math import sqrt

x = sqrt(2)
y = 2.0

if x * x == y:
  print("sqrt(2) times sqrt(2) is 2")
else:
  print("sqrt(2) times sqrt(2) is not two but %.8f" %(x * x))

EPSILON = 1E-14
if abs(x * x - y) < EPSILON:
  print("sqrt(2) times sqrt(2) is approximately 2")

